import numpy as np
import numpy.typing as npt

class IzhikevichNeuron:
    v: npt.NDArray[np.float64]
    u: npt.NDArray[np.float64]
    def __init__(self, n_units: int, dt: float) -> None: ...
    def reset_state(self) -> None: ...
    def update(self, x_in: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
    def size(self) -> int: ...

class DoubleExponentialSynapticFilter:
    r: npt.NDArray[np.float64]
    h: npt.NDArray[np.float64]
    def __init__(self, n_units: int, dt: float) -> None: ...
    def reset_state(self) -> None: ...
    def update(self, spikes: npt.NDArray[np.float64]) -> None: ...
    def size(self) -> int: ...

class SpikingNeuralNetwork:
    neurons: IzhikevichNeuron
    synapses: DoubleExponentialSynapticFilter
    x: npt.NDArray[np.float64]
    # v: npt.NDArray[np.float64]
    # u: npt.NDArray[np.float64]
    # r: npt.NDArray[np.float64]
    # h: npt.NDArray[np.float64]
    def __init__(
        self,
        n_units: int,
        in_size: int,
        out_size: int,
        dt: float,
        connection_ratio: float,
        G: float,
        Q: float,
        alpha: float,
        bias: float,
    ) -> None: ...
    def reset_state(self) -> None: ...
    def update(self, input: npt.NDArray[np.float64]) -> None: ...
    def train(self, teaching_signal: npt.NDArray[np.float64]) -> None: ...
    def size(self) -> int: ...
